apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  - port: 443
    protocol: TCP
    targetPort: 443
  - port: 8000
    protocol: TCP
    targetPort: 8000
  - port: 8001
    protocol: TCP
    targetPort: 8001
  - port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    app: api
