apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  strategy:
   rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        oreleans/serviceId: orleans-in-aks
        oreleans/clusterId: orleans-in-aks
    spec:
      containers:
      - name: api
        image: myregistry.azurecr.io/api:v1
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP     
        - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
          value: "true"
        - name: Orleans__Clustering__ProviderType
          value: "Redis"
        - name: Orleans__Clustering__ServiceKey
          value: "redis"
        - name: ConnectionStrings__redis
          valueFrom:
            secretKeyRef:
              name: redis-connection-string
              key: connectionString
        - name: ORLEANS-SILO-DASHBOARD
          value: "8000"
        - name: DOTNET_SHUTDOWNTIMEOUTSECONDS
          value: "120"
        ports:
        - containerPort: 8080
        - containerPort: 11111
        - containerPort: 30000
        - containerPort: 8000
      terminationGracePeriodSeconds: 180