apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: orleansgroupacr.azurecr.io/api:v15
        env:
        - name: ORLEANS_SERVICE_ID
          value: "orleans-in-aks"
        - name: ORLEANS_CLUSTER_ID
          value: "orleans-in-aks"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP     
        - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
          value: "true"
        - name: ConnectionStrings__redis
          valueFrom:
            secretKeyRef:
              name: redis-connection-string
              key: connectionString
        - name: ORLEANS-SILO-DASHBOARD
          value: "8000"
        ports:
        - containerPort: 8080
        - containerPort: 11111
        - containerPort: 30000
        - containerPort: 8000
