apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: LoadBalancer    
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  - port: 81
    protocol: TCP
    targetPort: 8000
  selector:
    app: api

